name: food_delivery_test_app_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.2.0
  go_router: ^8.0.3
  http: ^1.0.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  persistent_bottom_nav_bar: ^5.0.2
  stylish_bottom_bar: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.5
  build_runner: ^2.4.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
